---
version: '3'
services:
  umami:
    container_name: etz-umami
    ports:
      - "3000:3000"
    build:
      dockerfile: umami.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: etz-umami-db
    ports:
      - "5432:5432"
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: unless-stopped


  nginx:
    container_name: etz-umami-nginx
    user: root
    volumes:
      - ./env-variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
    build:
      dockerfile: nginx.Dockerfile
    env_file:
      - .env
    ports:
      - "8009:8082"
    environment:
      PORT: '8009' # This variable needs to match the outside port
    restart: unless-stopped

volumes:
  umami-db-data:
