---
version: '3'
services:
  umami:
    build: '.'
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data
    restart: always
volumes:
  umami-db-data:
