---
version: '3'
services:
  umami:
    build:
      dockerfile: umami.Dockerfile
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file:
      - .env
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - umami-db-data:/var/lib/postgresql/data

  nginx:
    container_name: Nginx
    volumes:
      - ./env-variables.conf:/etc/nginx/templates/10-variables.conf.template:ro
    build:
      dockerfile: nginx.Dockerfile
    env_file:
      - .env
    ports:
      - "8009:8082"
    environment:
      PORT: '8009' # This variable needs to match the outside port

volumes:
  umami-db-data:
